site_name: ProjectPath-Pro API
site_description: The ProjectPath-Pro API is the backend service designed to calculate critical paths and manage projects, activities, and its critical paths. It allows users to create and persist project data and identify critical tasks to optimize project timelines and resource allocation.
site_author: Gerson Vidal Alcantara

nav: 
    - Home: index.md
    - User Guide:
        - Introduction: guide/introduction.md
        - Getting Started: guide/getting_started.md
    - API Documentation: 
        - Introduction: api/introduction.md
        - Endpoints:
            - Important Considerations: api/endpoints/considerations.md
            - Projects:
                - Overview: api/endpoints/projects/overview.md
                - Request and Response Examples: api/endpoints/projects/examples.md
                - API Docs: api/endpoints/projects/docs.md
            - Activities:
                - Overview: api/endpoints/activities/overview.md
                - Request and Response Examples: api/endpoints/activities/examples.md
                - API Docs: api/endpoints/activities/docs.md
            - Critical Path:
                - Overview: api/endpoints/critical_path/overview.md
                - Request and Response Examples: api/endpoints/critical_path/examples.md
                - API Docs: api/endpoints/critical_path/docs.md
            - Authentication:
                - Overview: api/endpoints/authentication/overview.md
                - Request and Response Examples: api/endpoints/authentication/examples.md
                - API Docs: api/endpoints/authentication/docs.md

theme: 
    name: mkdocs
    user_color_mode_toggle: true


site_url: ""
use_directory_urls: false
